import { CuratedProduct, GuScoreBreakdown, ProductSource, ProductStatus } from "@/lib/curator/types";
import { computeGuScore } from "@/lib/curator/scoring";

interface Seed {
  name: string;
  categoryId: string;
  subcategoryId: string;
  shortDescription: string;
  description: string;
  editorNote: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  soldCount: number;
  shopName: string;
  source: ProductSource;
  style: string;
  styles: string[];
  color: string;
  material: string;
  dimensions: { width?: number; depth?: number; height?: number; note?: string };
  scores: GuScoreBreakdown;
  status: ProductStatus;
}

// Editorial voice note: every editorNote below is written the way a real
// curator would talk — a reason to choose it plus an honest caveat. This is
// the field most likely to surface on the public site later, so it is never
// filler text.
const seeds: Seed[] = [
  {
    name: "Sofa băng Hana 2m1 vải nỉ bố tháo vỏ",
    categoryId: "cat-sofa",
    subcategoryId: "sub-sofa-bang",
    shortDescription: "Chân gỗ thanh, tỷ lệ gọn, vỏ bọc tháo giặt được.",
    description:
      "Sofa băng dài 2m1, khung gỗ tự nhiên, bọc nỉ bố tháo rời giặt máy. Đệm ngồi mật độ vừa, không quá lún khi ngồi lâu. Chân gỗ vát nhẹ nâng thân sofa cách sàn 15cm nên nhìn thoáng hơn các mẫu bệt cùng kích thước.",
    editorNote:
      "Thiết kế chân gỗ thanh, tỷ lệ gọn và màu trung tính — hợp phòng khách 15–18m² theo hướng Japandi. Điểm mạnh thật sự là vỏ tháo giặt, thứ rất ít mẫu cùng tầm giá làm được. Nếu nhà có trẻ nhỏ thì đây là lý do chính để chọn. Không hợp nếu bạn muốn sofa sâu để nằm xem phim.",
    price: 7900000,
    originalPrice: 9500000,
    rating: 4.7,
    reviewCount: 264,
    soldCount: 412,
    shopName: "Oakwood Furniture",
    source: "manual",
    style: "Japandi",
    styles: ["Japandi", "Scandinavian", "Minimalism"],
    color: "Be ngà",
    material: "Khung gỗ sồi, vỏ nỉ bố",
    dimensions: { width: 210, depth: 85, height: 78 },
    scores: { visual: 88, style: 92, quality: 84, value: 80, editorial: 90 },
    status: "FEATURED",
  },
  {
    name: "Sofa góc chữ L Morra 2m6 vải tweed",
    categoryId: "cat-sofa",
    subcategoryId: "sub-sofa-goc",
    shortDescription: "Góc trái/phải đảo được, phù hợp phòng khách trên 20m².",
    description:
      "Sofa góc 2m6 với phần đuôi đảo chiều được khi lắp, phù hợp cả hai bố trí phòng. Vải tweed dệt dày, bám bụi ít hơn nhung. Khung gỗ thông sấy, chân kim loại đen.",
    editorNote:
      "Đuôi đảo chiều là chi tiết đáng tiền vì bạn không cần quyết định hướng phòng trước khi mua. Vải tweed nhìn có chất hơn nỉ trơn trong ảnh thật. Nhược điểm rõ: 2m6 là quá lớn cho phòng dưới 20m², đừng cố nhét vào.",
    price: 14500000,
    rating: 4.6,
    reviewCount: 98,
    soldCount: 143,
    shopName: "Oakwood Furniture",
    source: "manual",
    style: "Contemporary",
    styles: ["Contemporary", "Modern"],
    color: "Xám khói",
    material: "Vải tweed, khung gỗ thông",
    dimensions: { width: 260, depth: 160, height: 82 },
    scores: { visual: 82, style: 78, quality: 85, value: 72, editorial: 74 },
    status: "APPROVED",
  },
  {
    name: "Bàn trà tròn Kuro mặt gỗ sồi 80cm",
    categoryId: "cat-ban",
    subcategoryId: "sub-ban-tra",
    shortDescription: "Mặt tròn 80cm, không góc nhọn, hợp nhà có trẻ nhỏ.",
    description:
      "Bàn trà mặt tròn đường kính 80cm, gỗ sồi phủ dầu tự nhiên. Chân trụ ba chấu giúp không vướng chân khi ngồi sofa. Cao 42cm, ngang tầm mặt ngồi sofa tiêu chuẩn.",
    editorNote:
      "Mặt tròn là lựa chọn đúng cho phòng khách nhỏ vì không có góc nhọn chiếm lối đi. Phủ dầu thay vì sơn bóng nên vân gỗ thật lên rõ, đổi lại dễ để lại vòng nước nếu đặt ly lạnh trực tiếp — nên dùng kèm lót ly.",
    price: 3200000,
    originalPrice: 3900000,
    rating: 4.8,
    reviewCount: 187,
    soldCount: 356,
    shopName: "Mộc Decor",
    source: "manual",
    style: "Japandi",
    styles: ["Japandi", "Minimalism", "Wabi-Sabi"],
    color: "Nâu gỗ sồi",
    material: "Gỗ sồi phủ dầu",
    dimensions: { height: 42, note: "Đường kính 80cm" },
    scores: { visual: 90, style: 93, quality: 86, value: 85, editorial: 88 },
    status: "FEATURED",
  },
  {
    name: "Bàn ăn gỗ sồi Nara 1m4 mặt chữ nhật",
    categoryId: "cat-ban",
    subcategoryId: "sub-ban-an",
    shortDescription: "Đủ cho 4–6 người, gỗ sồi nguyên tấm ghép.",
    description:
      "Mặt bàn gỗ sồi ghép thanh dày 2.5cm, chân vát kiểu Bắc Âu. Kích thước 140x80cm phục vụ thoải mái 4 người, chen được 6 khi cần.",
    editorNote:
      "Dày 2.5cm là con số đáng chú ý — nhiều bàn cùng giá chỉ 1.8cm và cong nhẹ sau một năm. Đây là món mua một lần dùng mười năm. Cần lưu ý gỗ sồi sáng màu dễ lộ vết bẩn dầu mỡ, nên lau ngay sau bữa ăn.",
    price: 6800000,
    rating: 4.7,
    reviewCount: 142,
    soldCount: 219,
    shopName: "Oakwood Furniture",
    source: "manual",
    style: "Scandinavian",
    styles: ["Scandinavian", "Japandi", "Minimalism"],
    color: "Gỗ sồi tự nhiên",
    material: "Gỗ sồi ghép thanh",
    dimensions: { width: 140, depth: 80, height: 75 },
    scores: { visual: 84, style: 86, quality: 90, value: 82, editorial: 78 },
    status: "APPROVED",
  },
  {
    name: "Bàn làm việc Linden 120cm chân sắt",
    categoryId: "cat-ban",
    subcategoryId: "sub-ban-lam-viec",
    shortDescription: "Mặt 120x60cm, chân sắt không rung khi gõ phím.",
    description:
      "Bàn làm việc mặt MDF phủ melamine vân gỗ, chân sắt hộp sơn tĩnh điện có thanh giằng ngang. Có lỗ luồn dây phía sau.",
    editorNote:
      "Thanh giằng ngang là lý do mẫu này không rung khi gõ bàn phím cơ — chi tiết mà phần lớn bàn dưới 1.5 triệu bỏ qua. 120cm là mức tối thiểu hợp lý nếu bạn dùng thêm màn hình rời. Mặt melamine không sang bằng gỗ thật, đó là đánh đổi để có mức giá này.",
    price: 1290000,
    originalPrice: 1590000,
    rating: 4.5,
    reviewCount: 523,
    soldCount: 1340,
    shopName: "Workspace Co.",
    source: "manual",
    style: "Minimalism",
    styles: ["Minimalism", "Modern", "Industrial"],
    color: "Vân gỗ óc chó",
    material: "MDF phủ melamine, chân sắt",
    dimensions: { width: 120, depth: 60, height: 75 },
    scores: { visual: 70, style: 72, quality: 76, value: 90, editorial: 66 },
    status: "APPROVED",
  },
  {
    name: "Ghế ăn Nordic mặt gỗ tựa cong",
    categoryId: "cat-ghe",
    subcategoryId: "sub-ghe-an",
    shortDescription: "Tựa lưng cong ôm, xếp chồng được khi cất.",
    description:
      "Ghế ăn khung gỗ cao su tự nhiên, tựa lưng uốn cong theo dáng lưng. Mặt ngồi gỗ phẳng, có thể thêm nệm rời. Xếp chồng 3 chiếc khi cần dọn chỗ.",
    editorNote:
      "Tựa cong tạo khác biệt thật khi ngồi lâu so với ghế tựa thẳng cùng giá. Mua theo cặp sẽ hợp lý hơn vì phí ship tính theo kiện. Mặt gỗ trần hơi cứng nếu ngồi trên 45 phút — tính thêm nệm rời vào ngân sách.",
    price: 890000,
    rating: 4.6,
    reviewCount: 412,
    soldCount: 1820,
    shopName: "Nordic House VN",
    source: "manual",
    style: "Scandinavian",
    styles: ["Scandinavian", "Japandi"],
    color: "Gỗ tự nhiên",
    material: "Gỗ cao su",
    dimensions: { width: 45, depth: 50, height: 80 },
    scores: { visual: 82, style: 85, quality: 74, value: 88, editorial: 70 },
    status: "APPROVED",
  },
  {
    name: "Ghế thư giãn Lys khung gỗ bọc vải",
    categoryId: "cat-ghe",
    subcategoryId: "sub-ghe-thu-gian",
    shortDescription: "Góc ngả 15°, hợp góc đọc sách cạnh cửa sổ.",
    description:
      "Ghế bành khung gỗ tần bì, bọc vải linen pha, lưng ngả cố định 15°. Tay vịn gỗ liền khối. Kèm gối tựa lưng rời.",
    editorNote:
      "Đây là loại ghế nên đặt cạnh cửa sổ thành một góc riêng, không nên dùng làm ghế chính trong bộ tiếp khách. Khung gỗ tần bì cứng cáp hơn hẳn các mẫu khung thông. Vải linen pha thì đẹp nhưng bám lông thú cưng, cân nhắc nếu nuôi mèo.",
    price: 4200000,
    rating: 4.5,
    reviewCount: 76,
    soldCount: 94,
    shopName: "Nordic House VN",
    source: "manual",
    style: "Wabi-Sabi",
    styles: ["Wabi-Sabi", "Japandi", "Rustic"],
    color: "Xám tro",
    material: "Gỗ tần bì, vải linen pha",
    dimensions: { width: 70, depth: 78, height: 88 },
    scores: { visual: 86, style: 84, quality: 80, value: 70, editorial: 82 },
    status: "REVIEW",
  },
  {
    name: "Giường gỗ sồi Aso 1m8 đầu giường thấp",
    categoryId: "cat-giuong",
    subcategoryId: "sub-giuong-go",
    shortDescription: "Đầu giường thấp 35cm, hợp phòng trần thấp.",
    description:
      "Giường 1m8x2m khung gỗ sồi đặc, đầu giường thấp bản rộng. Giát phản gỗ nan liền, không cần mua thêm. Gầm cao 22cm đủ để hộp đựng đồ dẹt.",
    editorNote:
      "Đầu giường thấp là lựa chọn có chủ ý — trong phòng trần 2m7 phổ biến ở chung cư, đầu giường cao làm phòng trông nặng nề. Gỗ sồi đặc nên nặng, xác định vị trí trước khi lắp vì xê dịch sau đó rất vất vả.",
    price: 12500000,
    originalPrice: 14900000,
    rating: 4.8,
    reviewCount: 88,
    soldCount: 131,
    shopName: "Oakwood Furniture",
    source: "manual",
    style: "Japandi",
    styles: ["Japandi", "Minimalism", "Scandinavian"],
    color: "Nâu sồi nhạt",
    material: "Gỗ sồi đặc",
    dimensions: { width: 180, depth: 200, height: 85 },
    scores: { visual: 90, style: 94, quality: 92, value: 74, editorial: 86 },
    status: "FEATURED",
  },
  {
    name: "Tủ đầu giường Mune 2 ngăn kéo",
    categoryId: "cat-tu",
    subcategoryId: "sub-tu-dau-giuong",
    shortDescription: "Ray trượt giảm chấn, đóng êm không tiếng động.",
    description:
      "Tủ đầu giường hai ngăn kéo, ray trượt giảm chấn, mặt tủ 40x40cm đủ đặt đèn ngủ và sách. Tay nắm âm, không lộ kim loại.",
    editorNote:
      "Ray giảm chấn nghe như chi tiết nhỏ nhưng khác biệt thật khi bạn mở ngăn kéo lúc bạn đời đang ngủ. Tay nắm âm giúp mặt trước phẳng, hợp phòng ngủ tối giản. Mặt tủ chỉ 40cm nên không đặt được đèn cây đế lớn.",
    price: 1450000,
    rating: 4.6,
    reviewCount: 234,
    soldCount: 678,
    shopName: "Nordic House VN",
    source: "manual",
    style: "Minimalism",
    styles: ["Minimalism", "Japandi"],
    color: "Trắng ngà",
    material: "MDF phủ melamine",
    dimensions: { width: 40, depth: 40, height: 50 },
    scores: { visual: 76, style: 80, quality: 78, value: 84, editorial: 68 },
    status: "APPROVED",
  },
  {
    name: "Tủ quần áo cánh lùa Sena 1m6 có gương",
    categoryId: "cat-tu",
    subcategoryId: "sub-tu-quan-ao",
    shortDescription: "Cửa lùa không cần chừa khoảng mở, có gương soi toàn thân.",
    description:
      "Tủ quần áo rộng 1m6, hai cánh lùa, một cánh ốp gương toàn thân. Bên trong chia ngăn treo dài, ngăn treo ngắn và 3 ngăn kéo.",
    editorNote:
      "Cửa lùa là lựa chọn đúng cho phòng ngủ có lối đi hẹp vì không cần chừa 60cm khoảng mở cửa như tủ cánh bản lề. Gương tích hợp tiết kiệm được một món phải mua riêng. Ray lùa cần tra dầu sau khoảng 18 tháng, đừng bỏ qua việc này.",
    price: 8900000,
    rating: 4.4,
    reviewCount: 156,
    soldCount: 287,
    shopName: "SpaceFit Interior",
    source: "manual",
    style: "Modern",
    styles: ["Modern", "Minimalism", "Contemporary"],
    color: "Trắng phối vân gỗ",
    material: "MDF chống ẩm, gương cường lực",
    dimensions: { width: 160, depth: 60, height: 200 },
    scores: { visual: 72, style: 74, quality: 80, value: 76, editorial: 64 },
    status: "APPROVED",
  },
  {
    name: "Kệ sách Ryn 5 tầng khung thép mở",
    categoryId: "cat-ke",
    subcategoryId: "sub-ke-sach",
    shortDescription: "Khung thép mở, không gây cảm giác bí trong phòng nhỏ.",
    description:
      "Kệ sách 5 tầng, khung thép sơn tĩnh điện đen, tấm kệ gỗ dày 1.8cm. Không có tấm lưng nên nhìn xuyên qua được, phù hợp làm vách ngăn nhẹ.",
    editorNote:
      "Không có tấm lưng là ưu điểm chứ không phải thiếu sót — kệ hở dùng làm vách ngăn mềm giữa bàn làm việc và phòng khách rất tốt trong căn hộ một phòng. Tầng dưới cùng chịu lực kém hơn, đừng chất sách nặng ở đó.",
    price: 1890000,
    rating: 4.5,
    reviewCount: 312,
    soldCount: 890,
    shopName: "SteelFrame Home",
    source: "manual",
    style: "Industrial",
    styles: ["Industrial", "Modern", "Minimalism"],
    color: "Đen phối gỗ",
    material: "Thép sơn tĩnh điện, gỗ công nghiệp",
    dimensions: { width: 80, depth: 30, height: 180 },
    scores: { visual: 78, style: 80, quality: 76, value: 86, editorial: 72 },
    status: "APPROVED",
  },
  {
    name: "Kệ TV treo tường Flow 1m4",
    categoryId: "cat-ke",
    subcategoryId: "sub-ke-tv",
    shortDescription: "Treo tường, giải phóng toàn bộ diện tích sàn.",
    description:
      "Kệ TV treo tường dài 1m4, hai ngăn mở và một ngăn có cánh lật. Có rãnh đi dây âm phía sau. Chịu tải 40kg.",
    editorNote:
      "Treo tường làm phòng khách nhỏ trông thoáng hơn hẳn kệ đặt sàn — đây là một trong vài thay đổi rẻ tiền nhất mà hiệu quả thị giác rõ nhất. Điều kiện bắt buộc: tường gạch đặc hoặc bê tông, không lắp được trên vách thạch cao.",
    price: 2400000,
    rating: 4.4,
    reviewCount: 198,
    soldCount: 445,
    shopName: "SpaceFit Interior",
    source: "manual",
    style: "Minimalism",
    styles: ["Minimalism", "Modern"],
    color: "Trắng mờ",
    material: "MDF phủ laminate",
    dimensions: { width: 140, depth: 32, height: 30 },
    scores: { visual: 80, style: 78, quality: 74, value: 80, editorial: 70 },
    status: "APPROVED",
  },
  {
    name: "Đèn cây Sora chân gỗ ba chấu",
    categoryId: "cat-den",
    subcategoryId: "sub-den-cay",
    shortDescription: "Ánh sáng hắt trần, điểm nhấn góc phòng khách.",
    description:
      "Đèn cây cao 1m5, chân gỗ ba chấu, chao vải dệt. Ánh sáng 2700K hắt lên trần tạo lớp sáng gián tiếp. Công tắc chân dây.",
    editorNote:
      "Chân gỗ ba chấu khiến mẫu này trông như một món nội thất chứ không phải thiết bị chiếu sáng — đó là lý do nó đẹp cả khi tắt. Ánh sáng hắt trần rất hợp buổi tối xem phim, nhưng không đủ để đọc sách trực tiếp bên dưới.",
    price: 890000,
    originalPrice: 1090000,
    rating: 4.5,
    reviewCount: 367,
    soldCount: 812,
    shopName: "Lumina Home",
    source: "manual",
    style: "Scandinavian",
    styles: ["Scandinavian", "Japandi", "Minimalism"],
    color: "Be vải, chân gỗ sáng",
    material: "Gỗ tần bì, chao vải",
    dimensions: { height: 150, note: "Đường kính chao 40cm" },
    scores: { visual: 88, style: 88, quality: 78, value: 84, editorial: 84 },
    status: "FEATURED",
  },
  {
    name: "Đèn thả gốm Đất Nung dáng chuông",
    categoryId: "cat-den",
    subcategoryId: "sub-den-tha",
    shortDescription: "Gốm thủ công, mỗi chiếc có vân men riêng.",
    description:
      "Đèn thả chao gốm men mộc, dáng chuông, đường kính 28cm. Dây vải bọc dài 1m2 cắt ngắn được. Ánh sáng tập trung xuống mặt bàn.",
    editorNote:
      "Chao gốm thủ công nên vân men mỗi chiếc khác nhau — nếu bạn cần hai chiếc giống hệt nhau để treo đôi thì đây không phải lựa chọn đúng. Treo cách mặt bàn ăn 70–75cm là đẹp nhất. Cần khoan trần, không hợp nhà thuê ngắn hạn.",
    price: 620000,
    rating: 4.4,
    reviewCount: 143,
    soldCount: 398,
    shopName: "Đất Nung Décor",
    source: "manual",
    style: "Wabi-Sabi",
    styles: ["Wabi-Sabi", "Indochine", "Rustic"],
    color: "Nâu đất men mộc",
    material: "Gốm nung thủ công",
    dimensions: { note: "Đường kính chao 28cm, dây dài 120cm" },
    scores: { visual: 90, style: 86, quality: 76, value: 78, editorial: 92 },
    status: "APPROVED",
  },
  {
    name: "Gương tròn viền gỗ tần bì 60cm",
    categoryId: "cat-guong",
    subcategoryId: "sub-guong-treo",
    shortDescription: "Viền gỗ thật, treo lối vào hoặc cạnh sofa.",
    description:
      "Gương tròn đường kính 60cm, viền gỗ tần bì thật dày 2cm. Kính 5mm tráng bạc chống mốc. Kèm bộ treo tường.",
    editorNote:
      "Viền gỗ thật, không phải nhựa giả vân gỗ — cầm nặng tay hơn hẳn các mẫu cùng giá và đó là cách nhanh nhất để phân biệt. Treo đối diện cửa sổ sẽ nhân đôi ánh sáng tự nhiên cho phòng nhỏ. Cần hai người khi treo vì khá nặng.",
    price: 480000,
    rating: 4.6,
    reviewCount: 428,
    soldCount: 1120,
    shopName: "Mộc Decor",
    source: "manual",
    style: "Japandi",
    styles: ["Japandi", "Scandinavian", "Minimalism"],
    color: "Gỗ tần bì sáng",
    material: "Gỗ tần bì, kính tráng bạc",
    dimensions: { note: "Đường kính 60cm, dày 2cm" },
    scores: { visual: 86, style: 88, quality: 82, value: 90, editorial: 80 },
    status: "FEATURED",
  },
  {
    name: "Thảm dệt Kobo 160x230 sợi tái chế",
    categoryId: "cat-tham",
    subcategoryId: "sub-tham-phong-khach",
    shortDescription: "Dệt phẳng, mỏng 6mm, giặt máy được.",
    description:
      "Thảm dệt phẳng 160x230cm từ sợi cotton tái chế, dày 6mm nên không vướng cửa. Hoa văn kẻ chìm tông trung tính. Giặt máy ở chế độ nhẹ.",
    editorNote:
      "Mỏng 6mm là con số quan trọng — thảm dày hơn thường kẹt dưới cánh cửa phòng khách chung cư. Giặt máy được là lý do chính nên chọn mẫu này thay vì thảm lông. Đổi lại, thảm dệt phẳng không cho cảm giác êm chân như thảm lông xù.",
    price: 1650000,
    originalPrice: 1990000,
    rating: 4.5,
    reviewCount: 276,
    soldCount: 534,
    shopName: "Textile Nhà Việt",
    source: "manual",
    style: "Minimalism",
    styles: ["Minimalism", "Scandinavian", "Japandi"],
    color: "Kem phối xám",
    material: "Cotton tái chế",
    dimensions: { width: 160, depth: 230, note: "Dày 6mm" },
    scores: { visual: 80, style: 82, quality: 76, value: 82, editorial: 74 },
    status: "APPROVED",
  },
  {
    name: "Rèm vải linen Haze cản sáng 70%",
    categoryId: "cat-rem",
    subcategoryId: "sub-rem-vai",
    shortDescription: "Cản sáng 70%, vẫn giữ được ánh sáng dịu ban ngày.",
    description:
      "Rèm vải linen pha polyester, cản sáng khoảng 70%. Đầu rèm ore kim loại. Cao 2m7 phù hợp trần chung cư tiêu chuẩn.",
    editorNote:
      "Cản 70% là mức cân bằng tốt cho phòng khách — cản 100% làm phòng tối om ban ngày, thứ nhiều người hối hận sau khi lắp. Mẹo quan trọng: luôn treo rèm sát trần thay vì sát khung cửa, trần sẽ trông cao hơn rõ rệt.",
    price: 720000,
    rating: 4.3,
    reviewCount: 189,
    soldCount: 612,
    shopName: "Textile Nhà Việt",
    source: "manual",
    style: "Contemporary",
    styles: ["Contemporary", "Minimalism", "Scandinavian"],
    color: "Xám sương",
    material: "Linen pha polyester",
    dimensions: { width: 200, height: 270 },
    scores: { visual: 74, style: 76, quality: 72, value: 80, editorial: 70 },
    status: "REVIEW",
  },
  {
    name: "Bình hoa gốm men rạn dáng bầu",
    categoryId: "cat-decor",
    subcategoryId: "sub-binh-hoa",
    shortDescription: "Men rạn tự nhiên, cắm được cả hoa tươi và cành khô.",
    description:
      "Bình gốm dáng bầu cao 24cm, men rạn tự nhiên. Miệng hẹp 6cm giữ dáng bó hoa. Lòng bình tráng men kín, không thấm nước.",
    editorNote:
      "Men rạn nghĩa là mỗi chiếc có vân khác nhau — hãy coi đó là đặc điểm, không phải lỗi. Miệng hẹp giúp bó hoa đứng dáng mà không cần nhiều hoa, tiết kiệm hơn khi cắm hàng tuần. Với cành khô thì đây là món hoàn hảo.",
    price: 175000,
    rating: 4.4,
    reviewCount: 356,
    soldCount: 1480,
    shopName: "Đất Nung Décor",
    source: "manual",
    style: "Wabi-Sabi",
    styles: ["Wabi-Sabi", "Japandi", "Rustic"],
    color: "Trắng ngà men rạn",
    material: "Gốm men rạn",
    dimensions: { height: 24, note: "Đường kính bầu 16cm, miệng 6cm" },
    scores: { visual: 84, style: 86, quality: 74, value: 88, editorial: 82 },
    status: "APPROVED",
  },
  {
    name: "Tranh canvas bộ 3 tấm tông đất",
    categoryId: "cat-tranh",
    subcategoryId: "sub-tranh-canvas",
    shortDescription: "Bộ 3 tấm 40x60cm, có sẵn khung, treo được ngay.",
    description:
      "Bộ ba tranh canvas trừu tượng tông đất, mỗi tấm 40x60cm, khung gỗ mỏng màu tự nhiên. Đã căng sẵn, có móc treo phía sau.",
    editorNote:
      "Giải pháp nhanh để lấp mảng tường trống 1m5–2m mà không phải đầu tư tranh nghệ thuật. Tông đất dễ phối và không lỗi mốt nhanh như tranh màu mạnh. Nhìn gần sẽ thấy rõ chất liệu in, nên treo ở khoảng cách ngắm tự nhiên chứ đừng đặt sát tầm mắt.",
    price: 390000,
    rating: 4.2,
    reviewCount: 245,
    soldCount: 876,
    shopName: "Blank Canvas Studio",
    source: "manual",
    style: "Contemporary",
    styles: ["Contemporary", "Minimalism", "Modern"],
    color: "Nâu đất, be, kem",
    material: "Canvas in, khung gỗ thông",
    dimensions: { note: "3 tấm, mỗi tấm 40x60cm" },
    scores: { visual: 72, style: 74, quality: 64, value: 84, editorial: 68 },
    status: "REVIEW",
  },
  {
    name: "Chậu cây xi măng mài dáng trụ 30cm",
    categoryId: "cat-cay-chau",
    subcategoryId: "sub-chau-cay",
    shortDescription: "Xi măng mài mịn, có lỗ thoát nước và đĩa lót.",
    description:
      "Chậu xi măng mài dáng trụ cao 30cm, đường kính miệng 25cm. Có lỗ thoát nước đáy và đĩa lót đi kèm. Phù hợp cây cỡ trung như bàng Singapore nhỏ.",
    editorNote:
      "Xi măng mài cho cảm giác chắc chắn hơn hẳn chậu nhựa giả đá, và giữ ẩm đất tốt hơn trong khí hậu nóng. Rất nặng khi đầy đất — chọn vị trí đặt cố định trước khi trồng, vì sau đó bạn sẽ không muốn di chuyển nó.",
    price: 189000,
    rating: 4.5,
    reviewCount: 298,
    soldCount: 1050,
    shopName: "GreenGlow",
    source: "manual",
    style: "Minimalism",
    styles: ["Minimalism", "Industrial", "Tropical"],
    color: "Xám xi măng",
    material: "Xi măng mài",
    dimensions: { height: 30, note: "Đường kính miệng 25cm" },
    scores: { visual: 78, style: 80, quality: 76, value: 88, editorial: 70 },
    status: "APPROVED",
  },
  {
    name: "Bộ bàn ghế ban công mây nhựa 3 món",
    categoryId: "cat-ngoai-troi",
    subcategoryId: "sub-ban-ghe-ban-cong",
    shortDescription: "Mây nhựa chịu nắng mưa, gồm 2 ghế và 1 bàn nhỏ.",
    description:
      "Bộ ba món cho ban công: hai ghế đan mây nhựa tổng hợp khung thép và một bàn tròn mặt kính 45cm. Đệm ngồi rời có vỏ tháo giặt.",
    editorNote:
      "Mây nhựa tổng hợp chịu nắng mưa tốt hơn mây tự nhiên nhiều lần, đây là lựa chọn đúng cho ban công không có mái che hoàn toàn. Đệm ngồi thì vẫn phải cất vào trong khi mưa. Bộ này chỉ vừa ban công rộng từ 1m2 trở lên.",
    price: 2890000,
    originalPrice: 3400000,
    rating: 4.3,
    reviewCount: 167,
    soldCount: 389,
    shopName: "OutdoorLiving",
    source: "manual",
    style: "Tropical",
    styles: ["Tropical", "Contemporary", "Rustic"],
    color: "Nâu mây, đệm kem",
    material: "Mây nhựa tổng hợp, khung thép",
    dimensions: { note: "Bàn Ø45cm cao 55cm; ghế 60x60x80cm" },
    scores: { visual: 74, style: 72, quality: 74, value: 78, editorial: 66 },
    status: "DRAFT",
  },
  {
    name: "Khay gỗ óc chó chữ nhật 35cm",
    categoryId: "cat-phu-kien",
    subcategoryId: "sub-khay-go",
    shortDescription: "Gom đồ lặt vặt trên bàn console hoặc bàn trà.",
    description:
      "Khay gỗ óc chó 35x22cm, thành khay cao 2.5cm, tay cầm khoét âm hai đầu. Phủ dầu thực phẩm an toàn.",
    editorNote:
      "Món nhỏ nhưng là mẹo sắp xếp hiệu quả nhất cho bàn trà: mọi thứ lặt vặt bỏ vào khay lập tức trông có chủ đích thay vì bừa bộn. Gỗ óc chó thật nên giá cao hơn khay tre, đổi lại lên màu đẹp dần theo thời gian.",
    price: 320000,
    rating: 4.7,
    reviewCount: 134,
    soldCount: 467,
    shopName: "Mộc Decor",
    source: "manual",
    style: "Japandi",
    styles: ["Japandi", "Minimalism", "Wabi-Sabi"],
    color: "Nâu óc chó",
    material: "Gỗ óc chó phủ dầu",
    dimensions: { width: 35, depth: 22, height: 2.5 },
    scores: { visual: 82, style: 84, quality: 84, value: 76, editorial: 72 },
    status: "APPROVED",
  },
  {
    name: "Đèn ngủ cảm ứng chạm ba mức sáng",
    categoryId: "cat-den",
    subcategoryId: "sub-den-ban",
    shortDescription: "Chạm để đổi độ sáng, ánh vàng 2700K dễ ngủ.",
    description:
      "Đèn ngủ đầu giường cảm ứng chạm, ba mức sáng, ánh vàng ấm 2700K. Thân gốm, chao vải. Dùng điện trực tiếp, không pin.",
    editorNote:
      "2700K là con số đáng quan tâm — ánh trắng trên 4000K khiến não tỉnh táo, đó là lý do nhiều người khó ngủ dù đã tắt điện thoại. Cảm ứng chạm tiện hơn công tắc dây khi đang nằm. Không có điều khiển từ xa, nên đặt trong tầm với.",
    price: 259000,
    rating: 4.7,
    reviewCount: 1245,
    soldCount: 4820,
    shopName: "Warmlight Studio",
    source: "manual",
    style: "Minimalism",
    styles: ["Minimalism", "Japandi", "Scandinavian"],
    color: "Trắng ngà",
    material: "Gốm, chao vải",
    dimensions: { height: 32, note: "Đường kính đế 14cm" },
    scores: { visual: 78, style: 80, quality: 74, value: 92, editorial: 72 },
    status: "APPROVED",
  },
  {
    name: "Gương đứng toàn thân khung nhôm đen 1m6",
    categoryId: "cat-guong",
    subcategoryId: "sub-guong-dung",
    shortDescription: "Dựa tường hoặc treo, khung nhôm mảnh 1.5cm.",
    description:
      "Gương đứng 160x50cm, khung nhôm anodized đen bản mảnh 1.5cm. Dùng được cả hai kiểu: dựa tường có chân chống, hoặc treo tường bằng bộ ke đi kèm.",
    editorNote:
      "Khung mảnh 1.5cm là lý do mẫu này nhìn hiện đại thay vì nặng nề như gương khung gỗ dày. Linh hoạt dựa hoặc treo rất hợp nhà thuê. Nếu nhà có trẻ nhỏ, bắt buộc phải bắt vít cố định vào tường dù dùng kiểu dựa.",
    price: 1290000,
    rating: 4.5,
    reviewCount: 203,
    soldCount: 521,
    shopName: "SpaceFit Interior",
    source: "manual",
    style: "Modern",
    styles: ["Modern", "Minimalism", "Industrial"],
    color: "Đen nhám",
    material: "Nhôm anodized, kính 5mm",
    dimensions: { width: 50, height: 160 },
    scores: { visual: 82, style: 82, quality: 78, value: 82, editorial: 70 },
    status: "APPROVED",
  },
  {
    name: "Sofa đơn Kaya bọc nhung tuyết",
    categoryId: "cat-sofa",
    subcategoryId: "sub-sofa-don",
    shortDescription: "Ghế đơn bọc nhung, làm điểm nhấn màu trong phòng trung tính.",
    description:
      "Sofa đơn bọc nhung tuyết màu xanh rêu, chân gỗ vát. Đệm ngồi bọt biển mật độ cao. Kích thước gọn 68x72cm.",
    editorNote:
      "Đây là món dùng để phá thế đơn điệu của một phòng khách toàn tông trung tính — một điểm nhấn màu duy nhất thường hiệu quả hơn nhiều món màu rải rác. Nhung tuyết đẹp trong ảnh nhưng lộ vết chà xát và bám bụi, cần hút bụi định kỳ.",
    price: 3600000,
    rating: 4.3,
    reviewCount: 87,
    soldCount: 112,
    shopName: "Oakwood Furniture",
    source: "manual",
    style: "Luxury",
    styles: ["Luxury", "Contemporary", "Classic"],
    color: "Xanh rêu",
    material: "Nhung tuyết, chân gỗ cao su",
    dimensions: { width: 68, depth: 72, height: 78 },
    scores: { visual: 84, style: 76, quality: 70, value: 68, editorial: 76 },
    status: "REJECTED",
  },
];

function slugify(name: string) {
  return name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/gi, "d")
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

export const seedCuratedProducts: CuratedProduct[] = seeds.map((seed, index) => {
  const slug = slugify(seed.name);
  const createdAt = new Date(2026, 3, 2 + index, 9, 30).toISOString();
  return {
    id: `cur-${String(index + 1).padStart(3, "0")}`,
    name: seed.name,
    slug,
    categoryId: seed.categoryId,
    subcategoryId: seed.subcategoryId,
    description: seed.description,
    shortDescription: seed.shortDescription,
    image: `https://picsum.photos/seed/${slug}/1000/1250`,
    additionalImages: [1, 2, 3].map((n) => `https://picsum.photos/seed/${slug}-${n}/1000/1000`),
    price: seed.price,
    originalPrice: seed.originalPrice ?? null,
    currency: "VND" as const,
    rating: seed.rating,
    reviewCount: seed.reviewCount,
    soldCount: seed.soldCount,
    shopName: seed.shopName,
    source: seed.source,
    // DEMO placeholders. Real product/affiliate URLs are entered by hand in
    // the curator form — V2 never fabricates marketplace links.
    productUrl: `https://example.com/product/${slug}`,
    affiliateUrl: `https://example.com/affiliate/${slug}?demo=true`,
    style: seed.style,
    styles: seed.styles,
    color: seed.color,
    material: seed.material,
    dimensions: seed.dimensions,
    guScore: computeGuScore(seed.scores),
    scores: seed.scores,
    editorNote: seed.editorNote,
    status: seed.status,
    featured: seed.status === "FEATURED",
    createdAt,
    updatedAt: createdAt,
  };
});
